apiVersion: kubeone.io/v1alpha1
kind: KubeOneCluster

versions:
  kubernetes: '1.14.2'
cloudProvider:
  name: 'azure'
  cloudConfig: |
    {
      "tenantId": "${ARM_TENANT_ID}",
      "subscriptionId": "${ARM_SUBSCRIPTION_ID}",
      "aadClientId": "${ARM_CLIENT_ID}",
      "aadClientSecret": "${ARM_CLIENT_SECRET}",
      "resourceGroup": "mine-support-rg",
      "location": "westeurope",
      "subnetName": "mine-support-subnet",
      "routeTableName": "",
      "securityGroupName": "mine-support-sg",
      "vnetName": "mine-mupport-vpc",
      "primaryAvailabilitySetName": "mine-support-avset",
      "useInstanceMetadata": true,
      "useManagedIdentityExtension": false,
      "userAssignedIdentityID": ""
    }
